exclude: '.git|.tox'
default_stages: [commit, push]
fail_fast: true
default_language_version:
    python: python3.9

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: pipenv run pisort
        types: [ python ]

      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run tests
        types: [python]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language: python
        types: [ python ]
        args: [ '.',"--check" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
