exclude: '.git|.tox'
default_stages: [commit, push]
fail_fast: true
default_language_version:
    python: python3.9

repos:


  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        stages: [ commit ]
        language: python
        types: [ python ]
        args: [ '.',"--check" ]


