exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: local
    hooks:

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: pipenv run isort
        types: [ python ]


      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run tests
        types: [python]

