exclude: '.git|.tox'
default_stages: [commit, push]
fail_fast: true
default_language_version:
    python: python3.9

repos:
  - repo: local
    hooks:

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: pipenv run isort
        types: [ python ]


      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run tests
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.3
    hooks:
      - id: flake8
