"""Black list table.

Revision ID: 4756d9a5befc
Revises: 22134f28e5fe
Create Date: 2022-03-15 16:31:03.242194

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4756d9a5befc"
down_revision = "22134f28e5fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_lists",
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=244), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=244), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "todo_list_tasks",
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=244), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="taskpriority"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "IN_PROGRESS", "COMPLETED", "ARCHIVED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column("planned_start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=244), nullable=True),
        sa.Column("todo_list_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["todo_list_id"],
            ["todo_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.add_column(
        "blacklist_tokens",
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "blacklist_tokens",
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blacklist_tokens", "updated_on")
    op.drop_column("blacklist_tokens", "created_on")
    op.drop_table("todo_list_tasks")
    op.drop_table("todo_lists")
    # ### end Alembic commands ###
